# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-28 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20160527_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='contents',
            field=models.TextField(null=True),
        ),
    ]
