# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-28 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_inputtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcontents',
            name='label',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formvalues',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formcontents',
            name='input_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.InputType'),
        ),
        migrations.AlterField(
            model_name='formcontents',
            name='values',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.FormValues'),
        ),
    ]
