# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20160530_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formcontents',
            name='values',
        ),
        migrations.AddField(
            model_name='formvalues',
            name='list_of_values',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.FormContents'),
        ),
    ]
